create table admin_reconciliation_report (
    tenant_id varchar(128) not null,
    report_reference varchar(128) not null,
    currency_code varchar(3) not null,
    period_start timestamptz not null,
    period_end timestamptz not null,
    total_ledger_debits bigint not null,
    total_ledger_credits bigint not null,
    total_external_debits bigint not null,
    total_external_credits bigint not null,
    imbalance_amount bigint not null,
    status varchar(32) not null,
    reason_code varchar(64),
    resolution_notes varchar(512),
    approver_id varchar(128),
    checksum_sha256 varchar(64) not null,
    server_version bigint not null default 1,
    updated_at timestamptz not null,
    primary key (tenant_id, report_reference),
    check (status in ('BALANCED', 'IMBALANCED', 'RESOLVED', 'CLOSED')),
    check (total_ledger_debits >= 0),
    check (total_ledger_credits >= 0),
    check (total_external_debits >= 0),
    check (total_external_credits >= 0),
    check (imbalance_amount >= 0),
    check (server_version >= 0)
);

create index ix_reconciliation_report_status
    on admin_reconciliation_report (tenant_id, status);

create table admin_reconciliation_report_result (
    result_id uuid primary key,
    tenant_id varchar(128) not null,
    report_reference varchar(128) not null,
    query_fingerprint varchar(512) not null,
    evidence_reference varchar(128) not null,
    currency_code varchar(3) not null,
    period_start timestamptz not null,
    period_end timestamptz not null,
    total_ledger_debits bigint not null,
    total_ledger_credits bigint not null,
    total_external_debits bigint not null,
    total_external_credits bigint not null,
    imbalance_amount bigint not null,
    status varchar(32) not null,
    reason_code varchar(64),
    resolution_notes varchar(512),
    approver_id varchar(128),
    checksum_sha256 varchar(64) not null,
    server_version bigint not null,
    occurred_at timestamptz not null,
    idempotency_key varchar(128) not null,
    correlation_id varchar(128) not null,
    causation_id varchar(128) not null,
    unique (tenant_id, idempotency_key),
    foreign key (tenant_id, report_reference) references admin_reconciliation_report(tenant_id, report_reference),
    check (status in ('BALANCED', 'IMBALANCED', 'RESOLVED', 'CLOSED')),
    check (total_ledger_debits >= 0),
    check (total_ledger_credits >= 0),
    check (total_external_debits >= 0),
    check (total_external_credits >= 0),
    check (imbalance_amount >= 0),
    check (server_version >= 0)
);
